os: 
  - osx
  - linux
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq libegl1-mesa-dev libgles2-mesa-dev libxrandr-dev libsdl2-dev; fi 
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make