os: osx
language: cpp
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make

os: linux
before_install:
  - sudo apt-get install libxrandr-dev
  - sudo apt-get install libsdl2-dev
language: cpp
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make